apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: logback-app
  name: logback-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logback-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: logback-app
    spec:
      containers:
      - env:
        - name: NEW_RELIC_LICENSE_KEY
          value: <your-license-key-here>
        image: crshanks/logback-app:1.0
        name: logback-app
        resources: {}
      restartPolicy: Always
status: {}
